# Set 1
nn_opt:
    tio_prob_params:
        nn_name: neural_odometry_v2_single_new_loader
        imu_length: 20
        lr_rate: 0.0001
        rho: 0.9
        epsilon: 1e-08
        decay: 0.0
        fc_trans: 1
        fc_rot: 1
        flatten_rgb: 0
        n_mixture: 10
    loop_params:
        nn_name: neural_loop_closure_v2_single_new_loader
        img_h: 512
        img_w: 640
        img_c: 1
        epoch: 50
        batch_size: 8
        lr_rate: 0.001
        rho: 0.9
        epsilon: 1e-08
        decay: 0.0
        fc_trans: 1
        fc_rot: 1

# Set 2
os_odom_test:
    # model: neural_odometry_v2 # neural_loop_closure
    # model: neural_odometry_v2_6c_5e_10r # neural_loop_closure
    model: neural_odometry_v2_6c_5e_10r_FedTrimAvg # neural_loop_closure
    dataset: turtle # turtle (robot), handheld
    saved_dir_h5: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/odometry' # Replace with your data directory (respective odometry folder)
    gap: 5
    imu_length: 20
    n_mixture: 10
    test_dir: test # was "val" originally 

# Set 3
training_opt:
    dataset: turtle
    data_dir_turtle: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/odometry' # Replace with your data directory (odometry folder)
    rgb_feature_dir_turtle: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/odometry/rgb_features' # Replace with your data directory (RGB Feature folder)
    data_dir_handheld: '/mnt/data/hantaozhong/ti_slam_dataset/Handheld/odometry' # Replace with your data directory (odometry folder)
    rgb_feature_dir_handheld: '/mnt/data/hantaozhong/ti_slam_dataset/Handheld/odometry/rgb_features' # Replace with your data directory (RGB Feature folder)
    data_dir_mix: '/mnt/data/hantaozhong/ti_slam_dataset/Mix/odometry' # Replace with your data directory (odometry folder)
    rgb_feature_dir_mix: '/mnt/data/hantaozhong/ti_slam_dataset/Mix/odometry/rgb_features' # Replace with your data directory (RGB Feature folder)
    base_model_name: neural_odometry
    is_first_stage: 0 # False (0) or True (1), 1st stage to train hallucination. 2nd stage trains remaining.

# Set 4
train_loop_pose_opt:
    dataset: turtle # handheld

# Set 5
loop_robot_data:
    dataroot: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/raw'
    loop_path: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/loop'
    total_training: 9 # total 12, 9 train 3 val
    # all_exp_files:
    #     - 2019-10-24-18-08-33 # 12
    #     - 2019-10-24-18-24-40
    #     - 2019-10-24-18-21-18
    #     - 2019-10-24-18-16-24 # 15
    #     - 2019-10-24-18-13-21 
    #     - 2019-10-24-18-11-06
    #     - 2019-10-24-18-05-22
    #     - 2019-10-24-18-03-57
    #     - 2019-10-24-17-58-56 # 20
    #     - 2019-10-24-17-57-46 # val start
    #     - 2019-10-24-17-56-33
    #     - 2019-10-24-18-18-47 # 23
    all_exp_files:
        - 2019-10-24-18-08-33 # 12
        - 2019-10-24-18-24-40 # 13
        - 2019-10-24-18-21-18 # 14
        - 2019-10-24-18-16-24 # 15
        - 2019-10-24-18-13-21 # 16
        - 2019-10-24-18-11-06 # 17
        - 2019-10-24-18-05-22 # 18
        - 2019-10-24-18-03-57 # 19
        - 2019-10-24-17-58-56 # 20
        - 2019-10-24-17-55-21 # 27
        - 2019-10-24-17-53-58 # 28
        - 2019-10-24-18-06-56 # 29


# Set 6
loop_handheld_data:
    dataroot: '/mnt/data/hantaozhong/ti_slam_dataset/handeld/raw' # Replace with your data directory (handheld-raw folder)
    loop_path: '/mnt/data/hantaozhong/ti_slam_dataset/handeld/loop' # Replace with your data directory (handheld-loop folder)
    total_training: 18 # 24 total, 18 train, 6 val
    all_exp_files:
        - 2020-01-28-11-50-54 # 11
        - 2020-01-28-11-53-26
        - 2020-01-28-11-57-59
        - 2020-01-28-11-59-42
        - 2020-01-29-17-49-34 # 15
        - 2020-02-06-15-03-24 
        - 2020-02-06-15-07-25 
        - 2020-02-06-15-24-24 
        - 2020-02-06-15-29-15
        - 2020-02-06-15-48-35 # 20
        - 2020-02-06-15-58-41 
        - 2020-02-06-16-04-15 
        - 2020-02-06-16-15-45 
        - 2020-02-06-16-21-04 
        - 2020-02-07-16-09-47 # 25
        - 2020-02-07-16-25-22 
        - 2020-02-07-16-31-44
        - 2020-02-07-16-36-31
        - 2020-02-07-16-41-08 # 29 val start
        - 2020-02-07-16-46-50 # 30
        - 2020-02-07-17-00-15 
        - 2020-02-07-17-04-08
        - 2020-02-07-17-08-21
        - 2020-02-07-17-11-56 # 34     

# Set 3
mix_data:
    dataroot: '/mnt/data/hantaozhong/ti_slam_dataset/Mx/raw' # Replace with your data directory (handheld-raw folder)
    loop_path: '/mnt/data/hantaozhong/ti_slam_dataset/Mix/loop' # Replace with your data directory (handheld-loop folder)
    total_training: 18
    gap: 5
    all_exp_files:
        - 2019-10-24-18-08-33 # robot 12 (1)
        - 2019-10-24-18-24-40
        - 2019-10-24-18-21-18
        - 2019-10-24-18-16-24 # robot 15
        - 2019-10-24-18-13-21 # (5)
        - 2019-10-24-18-11-06 
        - 2019-10-24-18-05-22
        - 2019-10-24-18-03-57
        - 2019-10-24-17-58-56 # robot 20
        - 2020-01-28-11-50-54 # handheld 11 (10)
        - 2020-01-28-11-53-26
        - 2020-01-28-11-57-59
        - 2020-01-28-11-59-42
        - 2020-01-29-17-49-34 # handheld 15
        - 2020-02-06-15-03-24 # (15)
        - 2020-02-06-15-07-25 
        - 2020-02-06-15-24-24 
        - 2020-02-06-15-29-15 # handheld 19     
        - 2019-10-24-17-57-46 # val start robot 21
        - 2019-10-24-17-56-33 # robot 22 (20)
        - 2019-10-24-18-18-47 # robot 23
        - 2020-02-07-16-41-08 # handheld 29 
        - 2020-02-07-16-46-50 # handheld 30
        - 2020-02-07-17-00-15 # handheld 31     

# Set 7
loop_evaluation_opt:
    dataroot: '/mnt/data/hantaozhong/ti_slam_dataset/In-house_ground_robot/raw'
    loop_pairs_path: 'results/'
    # loop_detection_network: 'neural_embedding_v2_6c_5ep_10r_FedTrimAvg'
    # loop_detection_network: 'neural_embedding_v2_6c_5ep_10r'
    loop_detection_network: 'neural_embedding_v2_single_fp32'
    loop_threshold: 0.045
    model_name: neural_loop_closure_v2_single_fp32
    # model_name: neural_loop_closure_v2
    # exp_files:
    #     - 2019-10-24-17-55-21 # robot 27
    #     - 2019-10-24-17-53-58 # robot 28
    #     - 2019-10-24-18-06-56 # robot 29
    #     - 2019-10-24-17-51-58 # robot 30
    # exp_files:
    #     - 2020-01-28-11-28-50 # handheld 35
    #     - 2020-01-28-11-34-05 # handheld 36
    #     - 2020-01-28-11-39-07 # handheld 37
    #     - 2020-01-28-11-55-54 # handheld 38
    exp_files:
        - 2019-10-24-17-57-46 # 21
        - 2019-10-24-17-56-33 # 22
        - 2019-10-24-18-18-47 # 23
        - 2019-10-24-17-51-58 # 30


